### PR TITLE
Varying dark energy 2

### PR DESCRIPTION
**Pull request by adrianbayer**
Merged previous branch before testing equations were correct. Was missing factor 3. Corrected now and tested Omegas and H match CLASS. Note the number of halos at a = 0.6667 is around ~10 higher, but at a = 1 is a few 100 lower, when w0=-1.1 and wa=0.1.

### CODE REVIEW

**Comment by adrianbayer** [comment]
Note there is a bug in dE/da which is fixed in 
https://github.com/fastpm/fastpm/commit/b714897b49cac4907a9c212b341a2ffadb645941
https://github.com/fastpm/fastpm/commit/6d47be8fd988bb0749be7a59b466ea22f9a417e0

**Comment by rainwoodman** [comment]
What was the bug?

**Comment by adrianbayer** [comment]
A physical bug: when adding varying DE and curvature there are terms in dE/da and d2E/da2 due to d Omega_DE / da and d Omega_K / da etc that were missing.

**Comment by rainwoodman** [comment]
Thanks for clarifying!

**Comment by ClaudioNahmad** [comment]
Hello, i was wondering what would be the best way to add a dark energy equation of state different from w0wa-CDM? i noticed CPL is implemented but would like to add other equations. 

Also, is there a way to add a dark matter equation of state? 

greetings!

**Pull request merged**
