### PR TITLE
Varying dark energy

### PR DESCRIPTION
**Pull request by adrianbayer**
Allow input of w_0 and w_a for varying DE simulations.

### CODE REVIEW

**Comment by adrianbayer** [comment]
The only potential downside of this implementation is that even for constant DE runs, the Omega_DE_TimesHubbleEaSq function will be called when evaluating HubbleEa (instead of c->Omega_Lambda). Is that okay?

**Comment by rainwoodman** [comment]
Sure. I don't think it will make the code run much slower.

What about adding a 2 step simulation (modelled after nbodykit-ODE.lua), also as a demo of a typical value to enable this model?

**Comment by adrianbayer** [comment]
@rainwoodman I added a new lua file and a corresponding test to travis.yml. I only did nbodyki, not lightcone. Let me know if you meant both

**Comment by rainwoodman** [comment]
Just one coverage is good enough. We don't need to test the full matrix. 
Let's merge this. 

I hope the number of halos changed in a direction that we expect?

**Comment by adrianbayer** [comment]
Note there was a factor 3 missing, so I updated everything in the Varying dark energy 2 PR

**Pull request merged**
